### ISSUE TITLE
generated code is generating deprecated URLDecoder.decode() calls

### ISSUE THREAD

**Issue by kenkyee** [yongjhih/retrofit#1]
Retrofit_TestCreationApi.java:338: warning: [deprecation] decode(String) in URLDecoder has been deprecated
            this.path = java.net.URLDecoder.decode(httpUrl.encodedPath());

should be URLDecoder.decode(<string>, "UTF-8")

Minor issue...just causes build warnings but it's not harmful :-)

**Comment by yongjhih** [comment]
Thanks. Fixed: https://github.com/yongjhih/NotRetrofit/commit/f2fac79c46782e83ed8c50ae1a7bdfacd1148f7f
