### ISSUE TITLE
Using @Retrofit.Body with a method marked w/ @PUT doesn't emit body JSON

### ISSUE THREAD

**Issue by kenkyee** [yongjhih/retrofit#5]
Also tried using @Retrofit.PUT instead of @PUT but it makes no difference.
Swapping @PUT w/ @POST makes the body JSON get written.
Method declaration looks like this:

```
    @Retrofit.PUT("/api/site/{siteId}/campaign/{campaignId}")
    public abstract BaseResponse updateCampaign(@Header(Endpoints.HTTPHEADER_TOKEN) String authToken,
            @Retrofit.Path("siteId") String siteId,
            @Retrofit.Path("campaignId") long campaignId,
            @Retrofit.Body Campaign campaign);
```

@PUT is used for updating an object usually.  @POST is for creating new objects.

**Comment by yongjhih** [comment]
Sorry, `@PUT` is not supported with `@Body`, use `@Part` instead.

``` java
@PUT("/user/photo")
User updateUser(@Part("photo") RequestBody photo, @Part("description") RequestBody description);
```

`@POST` with `@Body`:

``` java
@POST("/users/new")
User createUser(@Body User user);
```

**Comment by kenkyee** [comment]
@Part doesn't emit stuff in JSON format...looks like this instead:

```
PUT /api/site/4/campaign/41 HTTP/1.1
SDK: 1.0
X-API-TOKEN: xJK8a75PKM6mcVNu5b8AvDQQs
Content-Type: multipart/form-data; boundary=163ecb4b-c498-4a92-baee-9ab9cdcea7e5
Content-Length: 283
Host: admin.raizlabs-sandbox.com
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/2.5.0

--163ecb4b-c498-4a92-baee-9ab9cdcea7e5
Content-Disposition: form-data; name="Status"
Content-Length: 14

active-running
--163ecb4b-c498-4a92-baee-9ab9cdcea7e5
Content-Disposition: form-data; name="Name"
Content-Length: 8

updated1
--163ecb4b-c498-4a92-baee-9ab9cdcea7e5--
```

While the server expects a JSON encoded body like you send up w/ a POST.
I tried leaving @Multipart off the method and it still uses the MIME multipart encoding.

**Comment by yongjhih** [comment]
Sorry, NotRetrofit is not supported PUT JSON body, supported PUT multipart only.

**Comment by kenkyee** [comment]
Had a quick look at NotRetrofit's source code...looks like RetrofitProcessor.java::buildBody() only executes if it's a POST but making it also accept a PUT should work too unless you mix in @Part parameters which wouldn't make sense.
Is there another technical reason it doesn't work?
Sorry for the questions...just trying to understand why because I think it's valid REST.

**Comment by yongjhih** [comment]
Nothing. Because I'm not sure whether it works fine, just disable it temporarily. Maybe you could test it.

**Comment by kenkyee** [comment]
Happy to...any beginner's guide on how to fork/test the library?
Simplest thing is probably to enable it temporarily in the next official release build :-)

**Comment by yongjhih** [comment]
You could test it by the following build.gradle to use specific package of commit via jitpack:

``` gradle
repositories {
    jcenter()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.yongjhih.NotRetrofit:retrofit:eb262c5264'
    apt 'com.github.yongjhih.NotRetrofit:retrofit-processor:eb262c5264'
}
```

If it works fine, I'll upload into jcenter.

**Comment by kenkyee** [comment]
It's generating correct code for translating @Body now, but it also adds another line that blanks out the body:
        requestBuilder.put(RequestBody.create(MediaType.parse(typedOutput.mimeType()), bodyString));
        requestBuilder.put(RequestBody.create(MediaType.parse(_MIME_APP_JSON_CHARSET_UTF8), ""));

It's adding the last line in the .vm around line 368.  I think you need a boolean flag that tracks whether you emitted a body already and if not, it adds that second line.

This affects @PUT and @POST currently.

**Comment by yongjhih** [comment]
Fixed duplicated Body:

``` gradle
    compile 'com.github.yongjhih.NotRetrofit:retrofit:1cc4afe5e1'
    apt 'com.github.yongjhih.NotRetrofit:retrofit-processor:1cc4afe5e1'
```

**Comment by kenkyee** [comment]
Thanks.  I even tried this which uses only the @Body as I expected it to do :-)

```
@PUT("/api/site/{siteId}/campaign/{campaignId}")
    public abstract Campaign updateCampaign(@Header(Endpoints.HTTPHEADER_TOKEN) String authToken,
            @Retrofit.Path("siteId") String siteId,
            @Retrofit.Path("campaignId") long campaignId,
            @Retrofit.Body Campaign campaign, @Retrofit.Part("Part") String part, @Retrofit.Field("field") String field
```

This is as expected because the Body should override everything else :-)
It's good for release..thanks for the quick fix.  :-)

**Comment by yongjhih** [comment]
You're welcome.
